import Head from "next/head";
import Image from "next/image";
import BeautyPortrait from "../components/BeautyPortrait";
import { Creativity } from "../components/Creativity";
import { Layout } from "../components/Layout";
import { LeadingBrand } from "../components/LeadingBrand";
import { OurCases } from "../components/OurCases";
import TrustProfessional from "../components/TrustProfessional";
import { WhatWeDo } from "../components/WhatWeDo";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Reto Web-Site</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <BeautyPortrait />
        <div style={{ height: "250px" }}></div>
        <TrustProfessional />
        <div style={{ height: "200px" }}></div>
        <WhatWeDo />
        <LeadingBrand />
        <Creativity />
        <div style={{ height: "200px" }}></div>
        <OurCases />
      </Layout>
    </div>
  );
}
